# Numpy 기본 - N차원 배열

In [1]:
import numpy as np

* 리스트 형태로 Numpy array 생성

In [6]:
array = np.array([2, 3, 4, 5, 6, 7])        # [] -> 리스트
array

array([2, 3, 4, 5, 6, 7])

In [7]:
type(array)

numpy.ndarray

* 튜플 형태로도 Numpy array 생성 가능

In [8]:
array = np.array((2, 3, 4, 5, 6, 7))        # () -> 튜플
array

array([2, 3, 4, 5, 6, 7])

In [9]:
type(array)

numpy.ndarray

* 리스트 형태로 배열 생성하여 계산하기

In [10]:
a = [1, 2, 3]
b = [4, 5, 6]

print(a + b)

[1, 2, 3, 4, 5, 6]


In [ ]:
print(a * b)        # 에러발생 -> 이유: 차원이 안맞음 (1, 3) * (1, 3)

TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
print(a[1]+b[1])

7


* Numpy 형태로 배열 생성하여 계산하기

In [14]:
a = np.array([1, 2, 3])     # 1차원 배열
b = np.array([4, 5, 6])     # 1차원 배열

print (a * b)

[ 4 10 18]


In [15]:
print(a + b)

[5 7 9]


In [16]:
print(a[1]+b[1])

7


## 0차원 배열

* Numpy 배열은 0차원부터 시작
* 0차원 배열: 스칼라 → 하나의 데이터값을 가진 배열로 볼 수 있다.
* shape() 함수는 배열이 무슨 차원으로 구성되어 있는지 보여줌 -> 0차원의 경우 반환값 X

In [19]:
arr = np.array(12)

print(arr)
print(np.shape(arr))        # 0차원 배열은 반환값 X

12
()


## 1차원 배열
* 1차원 배열: 벡터 → Numpy 배열의 가장 기본적 배열
* 1차원 배열은 파이썬 리스트와 동일한 형태

In [21]:
arr = np.array([2, 4, 6, 8, 10])        # 1차원 배열

print(arr)
print(np.shape(arr))        # 1-차원 배열에 대한 (5,)

[ 2  4  6  8 10]
(5,)


* 넘파이는 파이썬 리스트와 다르게 아래와 같이 특정 데이터로 채워진 배열을 손쉽게 만들 수 있다. 

In [23]:
print(np.zeros(5))          # 0으로 채워진 1차원 배열 생성

[0. 0. 0. 0. 0.]


In [25]:
print(np.ones(5))          # 1으로 채워진 1차원 배열 생성

[1. 1. 1. 1. 1.]


In [26]:
print(np.empty(5))      # 빈 배열 생성, 메모리 상태에 따라 값 달라짐

[1. 1. 1. 1. 1.]


In [29]:
# 일정 간격 배열 생성
print(np.arange(2, 20, 3))      # np.arange(시작, 끝, 간격)

[ 2  5  8 11 14 17]


In [31]:
# 선형 간격으로 배치된 값 배열 생성
print(np.linspace(0, 100, num=3))      # np.linespace(시작, 끝, 개수) 

[  0.  50. 100.]


* 넘파이는 1차원 배열을 한꺼번에 계산하는 벡터화 연산(vectorized operation)을 지원

In [32]:
arr1 = np.array([1, 3, 5])
arr2 = np.array([2, 4, 6])

print(arr1 * 2)
print(arr1 + arr2)

[ 2  6 10]
[ 3  7 11]


## 2차원 배열
* 2차원 배열: 행렬(Matrix)
* 테이블(표)형태와 같이 행과 열로 구성

넘파이에는 numpy.mat 라는 행렬 연산을 전문적으로 하는 모듈을 지원한다.

In [34]:
arr = np.array([[2, 4, 6], [1, 3, 5]])      # 2차원 배열 -> 2행 3열
print(arr)
print(np.shape(arr))        # 2차원 배열에 대한 (2, 3)

[[2 4 6]
 [1 3 5]]
(2, 3)


In [ ]:
arr = np.array([[2, 4], [6, 8], [10, 12]])  # 2차원 배열 -> 3행 2열
print(arr)
print(np.shape(arr))        # 2차원 배열에 대한 (3, 2)

[[ 2  4]
 [ 6  8]
 [10 12]]
(3, 2)


In [36]:
arr = np.array([[2, 4], [6, 8], [10, 12]]) 

print(len(arr))     # 행 개수
print(len(arr[0]))      # 열 개수

3
2


## 3차원 배열
* 3차원 이상의 배열: 텐서(Tensor)
* 3차원 배열은 2차원 배열을 몇번 사용하는지에 따라 깊이 결정

In [39]:
arr = np.array([[[111, 112, 113], [121, 122, 123]],[[211, 212, 213], [221, 222, 223]]])     # 3차원 배열
print(arr)
print(np.shape(arr))        # 3차원 배열에 대한 (2, 2, 3)  -> 가장 큰 덩어리부터 생각하면 되는듯

[[[111 112 113]
  [121 122 123]]

 [[211 212 213]
  [221 222 223]]]
(2, 2, 3)


In [41]:
print(len(arr))     # 깊이
print(len(arr[0]))     # 행 개수
print(len(arr[0][0]))     # 열 개수

2
2
3


# 배열 차원수 확인
* ndim 속성은 생성한 배열이 몇개의 차원으로 저장되어 있는지 정수 값으로 반환

In [43]:
a = np.array(12)
b = np.array([2, 4, 6, 8, 10])
c = np.array([[2, 4, 6], [1, 3, 5]])
d = arr = np.array([[[111, 121, 131], [211, 221, 231]], 
                    [[112, 122, 132], [212, 222, 232]]])

print(a.ndim)       # 0차원 배열
print(b.ndim)       # 1차원 배열
print(c.ndim)       # 2차원 배열
print(d.ndim)       # 3차원 배열

0
1
2
3


* shape 속성은 배열의 크기를 튜플로 반환

In [45]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.shape)        # (3, 4)
print(np.shape(arr))        # (3, 4)

(3, 4)
(3, 4)


# 배열 재구성
* 배열 재구성(reshape): 데이터 변경 없이 배열의 크기를 변경하는 것
* 배열의 크기를 변경할 때 원래 배열과 동일한 수의 데이터를 가져야 함
* 1차원 배열의 데이터 수 6개 -> reshape -> 2차원 배열 데이터 수 6개

## (1) 1차원 배열 → 2차원 배열
* reshape 메서드는 배열 재구성
* 배열에 저장된 데이터가 12개인 1차원 배열을 (4, 3) 형태 또는 (2, 6) 형태의 2차원 배열로 재구성

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new1 = arr.reshape(4, 3)
new2 = arr.reshape(2, 6)

print(new1, '\n')
print(new2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## (2) 1차원 배열 → 3차원 배열
* 배열에 저장된 데이터가 12 개인 1차원 배열을 (2, 3, 2) 형태의 3차원 배열로 재구성한다.

In [47]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]     # 리스트 형태

new1 = np.reshape(a, (4, 3))
new2 = np.reshape(a, (2, 6))

newarr = arr.reshape(2, 3, 2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

## (3) 배열의 차원 수 확장하기
* 넘파이의 newaxis 함수를 사용하여 기본 배열의 크기(차원 수)를 확장할 수 있음
* newaxis 함수는 배열의 크기를 한 차원 늘리는 것으로 1-차원 배열을 2-차원 배열로, 2-차원 배열을 3-차원 배열로 재구성해 줌

In [49]:
new = np.array([1, 2, 3, 4, 5, 6])
new.shape       # (6, )

(6,)

In [51]:
newarr = new[np.newaxis, :]
newarr.shape    # (1, 6)

(1, 6)

In [52]:
newarr = new[:, np.newaxis]
newarr.shape    # (6, 1)

(6, 1)

# Numpy 인덱싱 - 3차원만
* 파이썬 리스트(list)의 데이터를 인덱싱할 수 있는 것과 같이 넘파이 배열 또한 데이터를 인덱싱할 수 있다.
* 넘파이 배열의 인덱싱 방법은 리스트(list)의 인덱싱 방법과 동일하다. 즉 인덱스 번호를 참조하여 배열에 저장된 특정 데이터를 찾을 수 있다.
* 3차원 배열에서 특정 요소를 찾으려면 쉼표로 구분된 정수값를 사용하여 요소의 차원과 인덱스를 나타낼 수 있다.

In [53]:
arr = np.array([[[11, 12, 13], [14, 15, 16]],    
                [[21, 22, 23], [24, 25, 26]]])      # 3차원 배열
arr

array([[[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]]])

In [54]:
print(arr[0, 0, 0])
print(arr[1, 0, 0])

11
21


In [55]:
arr[1, 1, 2]

np.int64(26)

## 음수 인덱싱

In [ ]:
arr = np.array([2, 4, 6, 8])        # 1차원 음수 인덱싱
arr[-1]

np.int64(8)

In [57]:
arr = np.array([[2, 4, 6], [1, 3, 5]])      # 2차원 음수 인덱싱
arr[1, -2]

np.int64(3)

## 조건에 맞는 요소 인덱싱
* 특정 조건에 맞는 데이터만 인덱싱 가능

In [58]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr < 5     # Boolean 값 반환 (True, False)

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr[arr < 5]        # [ ] 안의 조건을 만족하는 arr만 추출

array([1, 2, 3, 4])

In [60]:
arr[arr > 8]

array([ 9, 10, 11, 12])

In [61]:
arr % 2 == 0        # Boolean 값 반환 (True, False)

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [62]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

# Numpy 슬라이싱
* 슬라이싱: 배열에서 여러개의 데이터를 한꺼번에 가져오는 것과 같이 특정 범위의 데이터를 잘라서 가져오는 것.
* 인덱스 대신 [시작:끝]으로 슬라이싱를 입력
* [시작:끝:단계]같이 슬라이싱에 단계를 정의 가능

In [64]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5]        # arr[0](2번째 숫자) 부터  arr[5] 전까지 (arr[4]까지)

array([2, 3, 4, 5])

* 인덱스 4의 위치에서부터 끝까지 데이터 슬라이싱

In [65]:
arr[4:]

array([5, 6, 7])

* 처음부터 인덱스 4의 위치까지 데이터 슬라이싱

In [66]:
arr[:4]

array([1, 2, 3, 4])

## 네거티브 슬라이싱
* 배열의 끝에서 역순으로 인덱스 -3 의 위치에서 부터 인덱스 -1의 위치까지 데이터를 슬라이싱 한다.

In [67]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [69]:
print(arr[-1:-8:-1])        # 맨 마지막 -1은 역순이라는 뜻인듯..?

[7 6 5 4 3 2 1]


## 단계별 슬라이싱
* 단계 값을 사용하여 슬라이싱 단계를 결정할 수 있다.
* 인덱스 1에서부터 인덱스 5까지의 요소를 2씩 증가하며 슬라이싱 한다.

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5:2]      # 맨 마지막 2 -> 2단계씩 증가하며 슬라이싱

array([2, 4])

In [72]:
arr[::2]        # 처음부터 끝까지 2씩 증가시키며 슬라이싱

array([1, 3, 5, 7])

## 2차원 배열 슬라이싱
* 두 번째 배열(2행)에서 인덱스 1에서부터 인덱스 4까지의 데이터를 슬라이싱 한다.
* arr[1, 1:4]에서 1은 두 번째 배열을 의미한다.

In [74]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[1, 1:4]     # 1 <- 2번째꺼 리스트에서 [1:4] <- 인덱스 1 ~ 4까지 데이터 슬라이싱

array([7, 8, 9])

* 두 개의 배열 모두에서 인덱스 2의 데이터를 슬라이싱

In [75]:
arr[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[0:2, 2]

array([3, 8])

* 두 개의 배열 모두에서 인덱스 1에서부터 인덱스 4로 슬라이싱하면 2차원 배열이 반환된다.

In [77]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

# Numpy 검색
* 배열에서 특정 값을 검색하여 일치하는 데이터의 인덱스를 반환
* 배열에서 원하는 값을 찾으려면 where( ) 메서드를 사용한다.

In [79]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)        # '4'가 저장된 인덱스를 반환

(array([3, 5, 6]),)


* 짝수 데이터에 대한 인덱스 검색

In [80]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 7]),)


* 홀수 데이터에 대한 인덱스 검색

In [81]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr % 2 == 1)
print(x)

(array([0, 2, 4, 6]),)


## argmax(), argmin() 메서드
* argmax() : 가장 큰 값의 위치(인덱스) 찾기
* argmin() : 가장 작은 값의 위치(인덱스) 찾기

In [83]:
arr = np.array([[11, 12, 13, 14, 15],
                [21, 22, 23, 24, 25]])
print(np.argmax(arr))
print(np.argmax(arr, axis=0))       # 열 축을 따라 가장 큰 값의 인덱스 찾기
print("---------------------")
print(np.argmin(arr))
print(np.argmin(arr, axis=1))       # 행 축을 따라 가장 작은 값의 인덱스 찾기

9
[1 1 1 1 1]
---------------------
0
[0 0]


## argwhere(), extract() 메서드
* argwhere() : 조건을 만족하는 값의 위치(인덱스) 찾기
* extract() : 조건을 만족하는 값을 추출한다.

In [84]:
arr = np.array([[31, 12, 33, 14, 35],
                [21, 22, 23, 24, 25]])

print(np.argwhere(arr==33))         # 조건을 만족하는 값의 위치(인덱스)를 반환
print(np.extract(arr > 30, arr))    # 조건을 만족하는 값을 추출

[[0 2]]
[31 33 35]


## searchshorted() 메서드
* 배열에서 검색 순서를 유지하기 위해 지정된 값이 삽입될 인덱스를 반환

In [85]:
arr = np.array([2, 4, 6, 8])
x = np.searchsorted(arr, 5)     # 5가 적절하게 삽입해야 하는 인덱스를 찾아줌
print(x)

2


* 배열에서 둘 이상의 값을 삽입되어야 할 인덱스를 찾아준다.

In [86]:
arr = np.array([2, 4, 6, 8])
x = np.searchsorted(arr, [1, 3, 5, 7])
print(x)

[0 1 2 3]


# Numpy 정렬
* 정렬은 배열 요소를 순서대로 배열하는 것을 말한다.
* 정렬된 순서는 숫자 또는 문자와 같은 요소를 오름차순 또는 내림차순 순서로 배열하는 것을 말한다.
* 넘파이 배열 객체에는 배열을 정렬하는 sort()라는 메서드가 있다.

In [87]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)
print(np.sort(arr))     # 실제 원본 데이터가 정렬되는건 아님

[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]


In [88]:
print(arr)
print(arr.sort()) # 배열 정렬 -> 일단 None 반환 -> 정렬데이터 저장
arr 

[2 1 5 3 7 4 6 8]
None


array([1, 2, 3, 4, 5, 6, 7, 8])

* 배열 내의 문자를 알파벳 순으로 정렬

In [89]:
arr = np.array(['seoul', 'ulsan', 'busan'])
np.sort(arr)

array(['busan', 'seoul', 'ulsan'], dtype='<U5')

* 정렬된 데이터의 원래 위치(인덱스)를 반환

In [90]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

print('원본 =', arr)
print('정렬 =', np.sort(arr))
print('위치 =', np.argsort(arr))        # 정렬되었을 때의 각 데이터의 원래 위치(인덱스)를 반환

원본 = [2 1 5 3 7 4 6 8]
정렬 = [1 2 3 4 5 6 7 8]
위치 = [1 0 3 5 2 6 4 7]


## 2차원 배열 정렬
* 2차원 배열에 sort() 메서드를 사용하면 각 행별로 정렬

In [91]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
np.sort(arr)        # 행 기준으로 정렬

array([[2, 3, 4],
       [0, 1, 5]])

* 열 기준 정렬

In [92]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
np.sort(arr, axis=1)    # 열 기준으로 정렬

array([[2, 3, 4],
       [0, 1, 5]])

# Numpy 병합
* 배열 병합: 두 개 이상의 배열의 값을 하나의 배열로 합치는 것
* SQL에서는 키를 기준으로 테이블을 병합하는 반면, 넘파이에서는 축(axis)을 기준으로 배열을 병합한다.
* 넘파이는 병합하려는 배열의 순서를 축과 함께 concatenate() 메서드에 전달한다. 축을 명확하게 입력하지 않으면 0으로 간주한다.

In [93]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

## 2차원 배열 병합 
* 두 개의 2차원 배열을 행(axis=1)을 기준으로 병합한다.

In [94]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## stack() 메서드 배열 병합
* stack() 메서드는 concatenate과 동일하게 작동하지만, stack() 메서드는 새로운 축을 따라 작동한다는 점에서 차이가 있다.
* 두 번째 축을 따라 두 개의 1차원 배열을 연결하여 서로 겹쳐서 쌓는 방식으로 병합한다.
* 병합하려는 배열 순서를 축과 함께 stack() 메서드에 전달한다. 축을 명확하게 입력하지 않으면 0으로 간주한다.

In [95]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

harr = np.hstack((arr1, arr2))
varr = np.vstack((arr1, arr2))
darr = np.dstack((arr1, arr2))

print(harr, '\n')
print(varr, '\n')
print(darr)

[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]] 

[[[1 4]
  [2 5]
  [3 6]]]
